import { Stepper, Title } from "@mantine/core";
import { IconAlpha, IconArrowIteration, IconArtboard, IconAssembly, IconAsset, IconAward, IconBow } from "@tabler/icons";
import Head from "next/head"
import { useState } from "react";
import BottomBar from "../components/bottombar/BottomBar";

export default function Process() {
    const [active, setActive] = useState(1);
    const nextStep = () => setActive((current) => (current < 4 ? current + 1 : current));
    const prevStep = () => setActive((current) => (current > 0 ? current - 1 : current));

    return (
        <>
            <Head>
                <title>Process | Griiken.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ marginLeft: '1rem' }}>

                <Title mb="1rem">Our Process</Title>
                <Stepper active={active} onStepClick={setActive} iconSize={50} orientation="vertical" maw="40rem">
                    <Stepper.Step icon={<IconAlpha />} color="teal" label="Get Initial Requiement" description="First steps toward breaking limits">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconArtboard />} label="Design" description="We design what you say">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconBow />} color="grape" label="Prototyping" description="We prototype what you say">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconArrowIteration />} color="indigo" label="Customer Evaluation" description="Customer revisions">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconAssembly />} label="Devlopment" description="We have done it!">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconAsset />}  color="yellow" label="Test" description="We have done it!">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Step icon={<IconAward />} color="green" label="Maintain" description="We have done it!">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Step>

                    <Stepper.Completed>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis perspiciatis similique, dicta accusamus voluptatum exercitationem aspernatur voluptas. Libero dolorum doloribus dignissimos voluptatem eligendi dicta vitae, assumenda fugit vero perspiciatis tempora?
                    </Stepper.Completed>
                </Stepper>
            </main>
            <BottomBar />
        </>
    );
}