import { Anchor, Avatar, Card, Group, Text, ThemeIcon, Title } from "@mantine/core";
import { IconArrowBounce } from "@tabler/icons";
import BottomBar from "../components/bottombar/BottomBar";
import AvaliableSolution from "../components/solutions/AvaliableSolutions";
import Head from "next/head";

export default function Solutions() {
  return (
    <>
      <Head>
        <title>Solution | Griiken.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ marginLeft: '1rem' }}>
        <Title>Our Projects</Title>
        <Card my="1rem" shadow="md" p="lg" radius="lg" withBorder w="20rem">
          <Card.Section>
            <div style={{
              width: '100%',
              height: '100px',
              backgroundColor: 'hsl(180, 50%, 30%)'
             }} />
          </Card.Section>

          <Group align="end" position="apart" mt='md'>
            <Text fz="lg" className="dmb">Manage Ark</Text>
            <Anchor align="center" component="a" href="https://www.google.com">
              <IconArrowBounce />
            </Anchor>
          </Group>
          <Text>This is our first project which is enterly based on the theme earth</Text>

        </Card>

        <Title mb="1rem" mt="4rem">We provide solution for</Title>
        <AvaliableSolution />
        <BottomBar />
      </main>
    </>
  )
}
